/*
 * Zybo Z7-10 QNN hardware smoke application.
 * Packet in:  0xA5 0x5A + 9,216 bytes of already-quantized 96x96 ROI.
 * Packet out: 0x5A 0xA5 + 25,920 raw-head bytes generated by FINN in PL.
 *
 * The PS only moves tensors through DMA and UART. The CNN/QNN MAC work is
 * performed by the FINN accelerator in the programmable logic.
 */
#include "xaxidma.h"
#include "xil_cache.h"
#include "xil_printf.h"
#include "xparameters.h"
#include "xstatus.h"
#include "xuartps.h"

#define INPUT_BYTES  9216U
/* 24 x 24 x 15 raw-head values, each serialized on a 24-bit AXI beat. */
#define OUTPUT_BYTES 25920U
#define RX_HEAD_0    0xA5U
#define RX_HEAD_1    0x5AU
#define TX_HEAD_0    0x5AU
#define TX_HEAD_1    0xA5U

static XAxiDma dma;
static XUartPs uart;
static u8 input_tensor[INPUT_BYTES] __attribute__((aligned(64)));
static u8 output_tensor[OUTPUT_BYTES] __attribute__((aligned(64)));

static int uart_read_exact(u8 *data, u32 count) {
    u32 received = 0;
    while (received < count) {
        received += XUartPs_Recv(&uart, data + received, count - received);
    }
    return XST_SUCCESS;
}

static void uart_write_exact(const u8 *data, u32 count) {
    u32 sent = 0;
    while (sent < count) {
        sent += XUartPs_Send(&uart, (u8 *)(data + sent), count - sent);
    }
}

static int dma_infer(void) {
    int status;
    Xil_DCacheFlushRange((UINTPTR)input_tensor, INPUT_BYTES);
    Xil_DCacheInvalidateRange((UINTPTR)output_tensor, OUTPUT_BYTES);

    status = XAxiDma_SimpleTransfer(&dma, (UINTPTR)output_tensor,
                                    OUTPUT_BYTES, XAXIDMA_DEVICE_TO_DMA);
    if (status != XST_SUCCESS) return status;
    status = XAxiDma_SimpleTransfer(&dma, (UINTPTR)input_tensor,
                                    INPUT_BYTES, XAXIDMA_DMA_TO_DEVICE);
    if (status != XST_SUCCESS) return status;

    while (XAxiDma_Busy(&dma, XAXIDMA_DMA_TO_DEVICE) ||
           XAxiDma_Busy(&dma, XAXIDMA_DEVICE_TO_DMA)) {}
    Xil_DCacheInvalidateRange((UINTPTR)output_tensor, OUTPUT_BYTES);
    return XST_SUCCESS;
}

int main(void) {
    XAxiDma_Config *dma_cfg;
    XUartPs_Config *uart_cfg;
    u8 byte;
    const u8 ok_header[2] = {TX_HEAD_0, TX_HEAD_1};
    const u8 err_header[2] = {0x45U, 0x52U};

    /* UART1 is the only enabled PS UART, therefore BSP instance index is 0. */
    uart_cfg = XUartPs_LookupConfig(XPAR_XUARTPS_0_DEVICE_ID);
    if (!uart_cfg || XUartPs_CfgInitialize(&uart, uart_cfg, uart_cfg->BaseAddress) != XST_SUCCESS)
        return XST_FAILURE;
    XUartPs_SetBaudRate(&uart, 115200);

    dma_cfg = XAxiDma_LookupConfig(XPAR_AXI_DMA_0_DEVICE_ID);
    if (!dma_cfg || XAxiDma_CfgInitialize(&dma, dma_cfg) != XST_SUCCESS)
        return XST_FAILURE;
    if (XAxiDma_HasSg(&dma)) return XST_FAILURE;

    xil_printf("Zybo QNN DMA UART ready\r\n");
    for (;;) {
        do { uart_read_exact(&byte, 1); } while (byte != RX_HEAD_0);
        uart_read_exact(&byte, 1);
        if (byte != RX_HEAD_1) continue;
        uart_read_exact(input_tensor, INPUT_BYTES);
        if (dma_infer() != XST_SUCCESS) {
            uart_write_exact(err_header, sizeof(err_header));
            continue;
        }
        uart_write_exact(ok_header, sizeof(ok_header));
        uart_write_exact(output_tensor, OUTPUT_BYTES);
    }
}
